export const ProductsData = [
    {
        id: 0,
        titulo: 'Hamburguesa vegana',
        descripcion: 'Hamburguesa de soja con lechuga y tomate',
        img: '/public/img/hamburguesas-de-soya.jpg',
        categoria: "CGluten",
        precio: 150,
    },
    {
        id: 1,
        titulo: 'Pizza vegana',
        descripcion: 'Pizza con queso vegano y vegetales',
        img: '/public/img/Pizza.jpg',
        categoria: "CGluten",
        precio: 150,
    },
    {
        id: 2,
        titulo: 'Tacos veganos',
        descripcion: 'Tacos con carne de soja y guacamole',
        img: '/public/img/tacos.jpg',
        categoria: "STACC",
        precio: 150,
    },
    {
        id: 3,
        titulo: 'Ensalada vegana',
        descripcion: 'Ensalada de lechuga, tomate y aguacate',
        categoria: "STACC",
        img: '/public/img/Ensalada.jpg',
        precio: 150,
    },
    {
        id: 4,
        titulo: 'Sushi vegano',
        descripcion: 'Sushi con arroz integral y vegetales',
        img: '/public/img/sushi.webp',
        categoria: "STACC",
        precio: 150,
    },
    {
        id: 5,
        titulo: 'Burrito vegano',
        descripcion: 'Burrito con frijoles y arroz integral',
        img: '/public/img/Burrito.png',
        categoria: "CGluten",
        precio: 150,
    },
    {
        id: 6,
        titulo: 'Wrap vegano',
        descripcion: 'Wrap con hummus y vegetales',
        img: '/public/img/wrap.jpg',
        categoria: "STACC",
        precio: 150,
    },
    {
        id: 7,
        titulo: 'Tarta vegana',
        descripcion: 'Tarta de manzana sin huevo ni lácteos',
        img: '/public/img/Tarta.jpg',
        categoria: "CGluten",
        precio: 150,
    },
    {
        id: 8,
        titulo: 'Galletas veganas',
        descripcion: 'Galletas de avena sin huevo ni lácteos',
        img: '/public/img/Galletas.png',
        categoria: "CGluten",
        precio: 150,
    },
    {
        id: 9,
        titulo: 'Batido vegano',
        descripcion: 'Batido de frutas con leche de almendras',
        categoria: "STACC",
        img:'/public/img/Batido.jpg',
        precio: 150,
    }
];
