export const ProductsData = [
    {
        id: 0,
        title: 'Hamburguesa Plant Grill',
        description: 'Hamburguesa de soja con lechuga y tomate',
        img: '/public/img/hamburguesas-de-soya.jpg',
        category: "CGluten",
        price: 150,
    },
    {
        id: 1,
        title: 'Pizza vegana',
        description: 'Pizza con queso vegano y vegetales',
        img: '/public/img/Pizza.jpg',
        category: "CGluten",
        price: 150,
    },
    {
        id: 2,
        title: 'Tacos veganos',
        description: 'Tacos con carne de soja y guacamole',
        img: '/public/img/tacos.jpg',
        category: "STACC",
        price: 200,
    },
    {
        id: 3,
        title: 'Ensalada',
        description: 'Ensalada de lechuga, tomate y aguacate con salsa de garbanzos',
        category: "STACC",
        img: '/public/img/Ensalada.jpg',
        price: 150,
    },
    {
        id: 4,
        title: 'Sushi NoFish',
        description: 'Sushi con arroz integral y vegetales',
        img: '/public/img/sushi.webp',
        category: "STACC",
        price: 150,
    },
    {
        id: 5,
        title: 'Burrito VegProtein',
        description: 'Burrito con frijoles y arroz integral',
        img: '/public/img/Burrito.png',
        category: "CGluten",
        price: 150,
    },
    {
        id: 6,
        title: 'Wrap vegano',
        description: 'Wrap con hummus y vegetales',
        img: '/public/img/wrap.jpg',
        category: "STACC",
        price: 150,
    },
    {
        id: 7,
        title: 'Tarta vegana',
        description: 'Tarta de manzana',
        img: '/public/img/Tarta.jpg',
        category: "CGluten",
        price: 150,
    },
    {
        id: 8,
        title: 'Galletas chips',
        description: 'Galletas de avena y chips de chocolate',
        img: '/public/img/Galletas.png',
        category: "CGluten",
        price: 150,
    },
    {
        id: 9,
        title: 'Batido Frutal',
        description: 'Batido de frutas con leche de almendras',
        category: "STACC",
        img:'/public/img/Batido.jpg',
        price: 150,
    }
];
